#!/bin/sh

SOURCE="x264"

FAT="x264-iOS"

SCRATCH="x264-iOS-scratch"

THIN=$(pwd)/"$SCRATCH/thin-x264"

CONFIGURE_FLAGS="--enable-static --enable-pic --disable-cli"

ARCHS="armv7 armv7s arm64 i386 x86_64"

IOS_DEPLOYMENT_TARGET="10.0"


rm -r $FAT
rm -r $SCRATCH

CWD=$(pwd)

for ARCH in $ARCHS
do
	echo "Building $ARCH..."

	ARCHDIR="$SCRATCH/$ARCH"

	mkdir -p $ARCHDIR
	cd $ARCHDIR

	CFLAGS="-arch $ARCH"
	ASFLAGS=

	if [ "$ARCH" = "i386" -o "$ARCH" = "x86_64" ]
	then
		PLATFORM="iPhoneSimulator"
		CFLAGS="$CFLAGS -mios-simulator-version-min=$IOS_DEPLOYMENT_TARGET"

		if [ "$ARCH" = "x86_64" ]
		then
			HOST=""
		else
			HOST="--host=i386-apple-darwin"
		fi
	else
		PLATFORM="iPhoneOS"

		if [ "$ARCH" = "arm64" ]
		then
			HOST="--host=aarch64-apple-darwin"
			XARCH="-arch aarch64"
		else
			HOST="--host=arm-apple-darwin"
			XARCH="-arch arm"
		fi

		CFLAGS="$CFLAGS -fembed-bitcode -mios-version-min=$IOS_DEPLOYMENT_TARGET"
		ASFLAGS="$CFLAGS"
	fi

	XCRUN_SDK=$(echo $PLATFORM | tr '[:upper:]' '[:lower:]')

	CC="xcrun --sdk $XCRUN_SDK clang"

	if [ $PLATFORM = "iPhoneOS" ]
	then
		export AS="$CWD/$SOURCE/tools/gas-preprocessor.pl $XARCH -- $CC"
	else
		export -n AS
	fi

	CXXFLAGS="$CFLAGS"
	LDFLAGS="$CFLAGS"

	CC=$CC $CWD/$SOURCE/configure \
		$CONFIGURE_FLAGS \
		$HOST \
		--extra-cflags="$CFLAGS" \
		--extra-asflags="$ASFLAGS" \
		--extra-ldflags="$LDFLAGS" \
		--prefix="$THIN/$ARCH" || exit 1

	make install || exit 1

	cd $CWD
done

echo "Building fat binaries..."

mkdir -p $FAT/lib
set - $ARCHS
CWD=$(pwd)
cd $THIN/$1/lib

for LIB in *.a
do
	cd $CWD
	lipo -create $(find $THIN -name $LIB) -output $FAT/lib/$LIB
done

cd $CWD
cp -rf $THIN/$1/include $FAT


